services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    container_name: auth-server
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - DB_NAME=${AUTH_DB_NAME}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - PASSWORD_SALT_ROUNDS=${PASSWORD_SALT_ROUNDS}
      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
    volumes:
      - ./services/auth/src:/auth/src
      - ./services/auth/config:/auth/config
      - ./services/auth/package-lock.json:/auth/package-lock.json
      - ./services/auth/package.json:/auth/package.json
      - ./services/auth/tsconfig.json:/auth/tsconfig.json
      - ./services/auth/node_modules:/auth/node_modules
    depends_on:
      - mongodb
    networks:
      - microservices-net

  event:
    build:
      context: ./services/event
      dockerfile: Dockerfile.dev
    container_name: event-server
    ports:
      - 3002:3000
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - DB_NAME=${EVENT_DB_NAME}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - PASSWORD_SALT_ROUNDS=${PASSWORD_SALT_ROUNDS}
      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - AUTH_API_URI=${AUTH_API_URI}
    volumes:
      - ./services/event/src:/event/src
      - ./services/event/config:/event/config
      - ./services/event/package-lock.json:/event/package-lock.json
      - ./services/event/package.json:/event/package.json
      - ./services/event/tsconfig.json:/event/tsconfig.json
      - ./services/event/node_modules:/event/node_modules
    depends_on:
      - mongodb
    networks:
      - microservices-net

  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile.dev
    container_name: gateway-server
    ports:
      - 3000:3000
    environment:
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - ACCESS_TOKEN_EXPIRES_IN=${ACCESS_TOKEN_EXPIRES_IN}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - EVENT_SERVICE_HOST=${EVENT_SERVICE_HOST}
      - EVENT_SERVICE_PORT=${EVENT_SERVICE_PORT}
    volumes:
      - ./services/gateway/src:/gateway/src
      - ./services/gateway/config:/gateway/config
      - ./services/gateway/package-lock.json:/gateway/package-lock.json
      - ./services/gateway/package.json:/gateway/package.json
      - ./services/gateway/tsconfig.json:/gateway/tsconfig.json
      - ./services/gateway/node_modules:/gateway/node_modules
    networks:
      - microservices-net

  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - microservices-net

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo:
  redis: